version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the JavaScript app...
      # Add any build commands if needed, or remove if not applicable
artifacts:
  files:
    - '**/*'
